Properties:
  domain: studycatalog.cancer.gov
  rel_prop_delimiter: "$"

  plurals:
    dataset: datasets
    grant: grants
    program: programs
    project: projects
    publication: publications

  type_mapping:
    list: String
    string: String
    number: Float
    integer: Int
    boolean: Boolean
    array: Array
    object: Object
    datetime: DateTime
    date: Date
    TBD: String

  id_fields:
    dataset: dbGaP_phs
    grant: grant_id
    program: program_id
    project: project_id
    publication: pmid